:- use_module(library(clpfd)).

puzzle(Zeb, Agua):-
    Nac = [Ing, Esp, Nor, Por, Ucr],
    Beb = [Sumo, Cha, Cafe, Leite, Agua],
    Cor = [Verm, Ver, Bran, Amar, Azul],
    Tab = [Che, Win, LS, SG, Mar],
    Anim = [Cao, Rap, Igu, Cav, Zeb],
    L = [Nac, Cor, Beb, Tab, Anim],
    List = [Ing, Esp, Nor, Por, Ucr, Sumo, Cha, Cafe, Leite, Agua, Verm, Ver, Bran, Amar, Azul,
Che, Win, LS, SG, Mar, Cao, Rap, Igu, Cav, Zeb],
    domain(List, 1, 5),
    all_distinct(Nac), all_distinct(Cor), all_distinct(Beb), all_distinct(Tab), all_distinct(Anim),
    Ing #= Verm,
    Esp #= Cao,
    Nor #= 1,
    Amar #= Mar,
    abs(Che - Rap) #= 1,
    abs(Nor - Azul) #= 1,
    Win #= Igu,
    LS #= Sumo,
    Ucr #= Cha,
    Por #= SG,
    abs(Mar - Cav) #= 1,
    Ver #= Cafe,
    Ver #= (Bran + 1),
    Leite #= 3,
    labelin, g([], List),
    write(L), nl.
